apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: todolist-keyvault
  labels: 
    azure.azureauthority.in: aks-apps
    app: asset-manager
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: c33166a7-a9a8-4ff4-acbd-dbb19c0a67d9
    keyvaultName: kvproject3afnan
    objects:  |
      array:
        - |
          objectName: config
          objectType: secret
          objectAlias: config.json
    tenantId: cf36141c-ddd7-45a7-b073-111f66d0b30c